#!/usr/bin/env python3


class ExpectedError(Exception):
    def __init__(self, message):
        """An ExpectedError is an Exception that is generated by git-ssh"""
        super(ExpectedError, self).__init__(message)
