#!/bin/sh

#  Copyright (C) 2025 pyamsoft
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

# A pre-commit hook that runs all pre-commit hooks ending with .pre-commit
# in order
HOOK_DIR="$(realpath "$(dirname "$0")")"
readonly HOOK_DIR

main() {
  LC_ALL=C
  export LC_ALL

  for _hook in "${HOOK_DIR}"/*.pre-commit; do
    # No hooks
    if [ "${_hook}" = './*.pre-commit' ]; then
      return 0
    fi

    if [ -x "${_hook}" ]; then
      # Run the hook directly
      "${_hook}" "$@" || return 1
    else
      # Otherwise run with shell if its not executable
      /bin/sh "${_hook}" "$@" || return 1
    fi
    unset _hook
  done
  unset _hook

  return 0
}

main "$@" || exit 1
exit 0
